apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secret-store-sample
spec:
  provider:
    gcpsm:
      projectID: gke-practice-341914
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: us-east1
          # name of the GKE cluster
          clusterName: gke-cluster-demo
          # reference the sa from above
          serviceAccountRef:
            name: secret-ksa
            namespace: default