apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: externalsecret
  namespace: green-ns
spec:
  refreshInterval: 1s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-sample         # name of the SecretStore (or kind specified)
  target:
    name: secret-created  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: my-secret-key  # name of the GCPSM secret key
    remoteRef:
      key: my-secret