apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: blue-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template: 
    metadata:
      name: flask-app
      labels: 
        app: flask-app      
    spec:
      containers:
        - name: flask-app
          image: akhilmovva/flask-image:dev
          env: 
            - name: ENV
              value: "blue"
            - name: MYSQL_HOST
              value: "mysql-release"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-created
                  key: my-secret-key
            - name: API_TOKEN_2
              valueFrom:
                secretKeyRef:
                  name: secret-created
                  key: my-api-key
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: blue-ns
  labels: 
    app: flask-app
spec:
  # type: ExternalName #LoadBalancer  
  selector:
    app: flask-app
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 5000 # Container Port
      # nodePort: 31213 # NodePort